/**
 * Build stamps for the game's built files (M8, widened after the learner's iPhone showed the
 * menu icons scrambled — a new menu.json read against an old cached menu.png): a short content
 * hash of every file under public/world/{art,maps,content,minis} and of the voice index,
 * written into `src/world/ui/stamps.gen.ts`. `stamped()` (ui/stamped.ts) puts it on the URL,
 * so a URL changes whenever its file does and a browser never mixes an old file with a new one.
 * Every `npm run world:*` build rewrites it (`npm run world:stamps` alone too); `npm run
 * world:check` fails when it no longer matches the files.
 *
 *   npx tsx scripts/world/stamps.ts
 */

import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

export const STAMP_FILE = 'src/world/ui/stamps.gen.ts';
/** the folders whose every file is stamped, and single files besides */
const DIRS = ['world/art', 'world/maps', 'world/content', 'world/minis'];
const FILES = ['world/voice/index.json'];

const hash = (bytes: Buffer) => createHash('sha1').update(bytes).digest('hex').slice(0, 10);

/** The stamps module for the files under `root` (the repo). */
export function stampModule(root = '.'): string {
  const pub = join(root, 'public');
  const paths = [
    ...DIRS.flatMap((d) => (existsSync(join(pub, d)) ? readdirSync(join(pub, d)).filter((f) => /\.(png|json)$/.test(f)).map((f) => `${d}/${f}`) : [])),
    ...FILES.filter((f) => existsSync(join(pub, f))),
  ].sort();
  return [
    '// Generated by scripts/world/stamps.ts (every npm run world:* build) — do not edit.',
    '// A content hash per built file, put on its URL (ui/stamped.ts) so a browser never mixes old and new.',
    '',
    'export const STAMPS: Readonly<Record<string, string>> = {',
    ...paths.map((p) => `  '${p}': '${hash(readFileSync(join(pub, p)))}',`),
    '};',
    '',
  ].join('\n');
}

export function writeStamps(root = '.'): void {
  writeFileSync(join(root, STAMP_FILE), stampModule(root));
}

/** An error when the stamps module does not match the built files. */
export function checkStamps(root = '.'): string | null {
  const path = join(root, STAMP_FILE);
  if (!existsSync(path)) return `${STAMP_FILE} is missing — run npm run world:stamps`;
  return readFileSync(path, 'utf8') === stampModule(root) ? null : `${STAMP_FILE} is out of date with the built files under public/world — run npm run world:stamps`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) writeStamps();
