/**
 * Build stamps for the built map files the plans load (M8): a short content hash of
 * `public/world/maps/hoods.json` and of every `public/world/minis/<map>.png`, written into
 * `src/world/ui/stamps.gen.ts`, so their URLs change whenever the files do and a browser never
 * keeps an old picture. `npm run world:maps` and `npm run world:minis` both rewrite it;
 * `npm run world:check` fails when it no longer matches the files.
 */

import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const STAMP_FILE = 'src/world/ui/stamps.gen.ts';

const hash = (bytes: Buffer) => createHash('sha1').update(bytes).digest('hex').slice(0, 10);

/** The stamps module for the files under `root` (the repo). */
export function stampModule(root = '.'): string {
  const hoodsPath = join(root, 'public/world/maps/hoods.json');
  const hoods = existsSync(hoodsPath) ? hash(readFileSync(hoodsPath)) : '';
  const dir = join(root, 'public/world/minis');
  const minis = existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith('.png'))
        .sort()
        .map((f) => `  '${f.slice(0, -4)}': '${hash(readFileSync(join(dir, f)))}',`)
    : [];
  return [
    '// Generated by scripts/world/stamps.ts (npm run world:maps / world:minis) — do not edit.',
    '// A content hash per built file, put on its URL so a browser never shows a stale one.',
    '',
    `export const HOODS_STAMP = '${hoods}';`,
    '',
    'export const MINI_STAMPS: Readonly<Record<string, string>> = {',
    ...minis,
    '};',
    '',
  ].join('\n');
}

export function writeStamps(root = '.'): void {
  writeFileSync(join(root, STAMP_FILE), stampModule(root));
}

/** An error when the stamps module does not match the built files. */
export function checkStamps(root = '.'): string | null {
  const path = join(root, STAMP_FILE);
  if (!existsSync(path)) return `${STAMP_FILE} is missing — run npm run world:minis`;
  return readFileSync(path, 'utf8') === stampModule(root) ? null : `${STAMP_FILE} is out of date with the built maps and miniatures — run npm run world:minis`;
}
