"""
What the 214 Kangxi radicals are, written by hand.

No dataset carries this. Make Me a Hanzi says which component of a character is
its radical and hanziDB gives the Kangxi number, but neither knows that 心 is
written three ways, that 阝 is two different radicals depending on the side it
sits on, or that 王 on the left of 玩 means jade. The build used to guess the
written forms by voting among the characters that use each radical, which
produced 贝 as a "variant" of 宀 and 心 as a variant of 八 — and those went on to
gloss 心 as "eight" on every character sheet that showed it as a part.

So each radical is described here once: what it means, what it is called, what
it gets mistaken for, and every distinct way it is written. A written form names
the character its outline is cut from, so the practice squares show it at the
size and position it really has inside a character.

A form earns its own entry when it is written differently, not merely smaller:
忄 and 心 are different shapes, and so is 土 on the left of 地, where the last
stroke rises instead of lying flat. 口 on the left of 吃 is only a smaller 口,
so it is one form.

`scripts/build_radicals.py` checks every entry against the sources and fills in
the counts, the examples and the outlines.
"""
from __future__ import annotations

# Where a form sits in the characters that use it.
ALONE = "alone"
LEFT = "left"
RIGHT = "right"
TOP = "top"
BOTTOM = "bottom"
TOP_LEFT = "topLeft"  # 广 厂 尸 疒: over the top and down the left
BOTTOM_LEFT = "bottomLeft"  # 辶 廴 走: along the bottom and up the left
TOP_RIGHT = "topRight"  # 勹 气: over the top and down the right
AROUND = "around"  # 囗: all the way round

POSITIONS = (ALONE, LEFT, RIGHT, TOP, BOTTOM, TOP_LEFT, BOTTOM_LEFT, TOP_RIGHT, AROUND)


def N(hanzi: str, pinyin: str) -> tuple[str, str]:
    """A colloquial name: 三点水, sān diǎn shuǐ."""
    return (hanzi, pinyin)


def F(g, pos=ALONE, host=None, part=None, name=None, tip=None, ex=None):
    """
    One written form of a radical.

    `host` is the character the outline is cut from, and `part` the component
    as that character's decomposition spells it when that differs from the form
    itself — the ⻊ of 跑 is spelled 足. A form with no host is drawn from its
    own outline, full size: that is what `ALONE` means.

    `ex` replaces the examples the build would otherwise pick, for forms the
    dictionaries file under some other radical (the ⺈ of 负 and 色 is under 贝
    and 色, not 刀).
    """
    return {
        "g": g,
        "pos": pos,
        "host": host,
        "part": part or g,
        "name": name,
        "tip": tip,
        "ex": ex,
    }


def R(mean, py, *, word=None, r=None, about=None, note=None, forms=None, name=None, ex=None):
    """
    One radical.

    `mean` is what it means as a part of other characters, which is not always
    what the character means on its own. `word` is the character the radical is
    named after and `py` its reading — 心 xīn for 忄. `about` says what the
    characters built on it tend to be about; it is left out where the honest
    answer is "nothing in particular". `note` is the look-alike warning.

    A radical with no `forms` is written one way, and that way is `r` (or the
    Kangxi form) on its own; `name` and `ex` then belong to that single form.
    """
    return {
        "mean": mean,
        "py": py,
        "word": word,
        "r": r,
        "about": about,
        "note": note,
        "forms": forms,
        "name": name,
        "ex": ex,
    }


RADICALS: dict[int, dict] = {
    1: R("one", "yī", name=N("横", "héng"), about="The number one, or just a flat stroke"),
    2: R("vertical line", "gǔn", r="丨", name=N("竖", "shù")),
    3: R("dot", "zhǔ", r="丶", name=N("点", "diǎn")),
    4: R("slash", "piě", r="丿", name=N("撇", "piě")),
    5: R("second; a bent stroke", "yǐ", forms=[
        F("乙", ex="九乞"),
        F("乚", RIGHT, host="乱", name=N("竖弯钩", "shù wān gōu"),
          tip="Only the bent stroke, closing off the right-hand side", ex="乱乳也"),
    ]),
    6: R("hook", "jué", r="亅", name=N("竖钩", "shù gōu")),
    7: R("two", "èr"),
    8: R("lid", "tóu", forms=[F("亠", TOP, host="京", name=N("点横头", "diǎn héng tóu"))]),
    9: R("person", "rén", word="人", about="People, and what people do",
         note="One slash is a person (你); two slashes, 彳, is a road (往).",
         forms=[
             F("亻", LEFT, host="你", name=N("单人旁", "dān rén páng"),
               tip="The person turned sideways: a slash, then an upright"),
             F("人", TOP, host="会", name=N("人字头", "rén zì tóu"),
               tip="Spread wide, like a roof over the part below"),
         ]),
    10: R("legs; child", "ér", about="Legs: a person walking",
          forms=[F("儿", BOTTOM, host="先", name=N("儿字底", "ér zì dǐ"))]),
    11: R("enter", "rù",
          note="入: the left stroke leans on the right. 人: the right leans on the left. 八: they don't touch."),
    12: R("eight", "bā", forms=[
        F("八"),
        F("丷", TOP, host="关", tip="The two strokes turned to point inwards, on top"),
    ]),
    13: R("borders", "jiōng", name=N("同字框", "tóng zì kuàng")),
    14: R("cover", "mì", note="No dot on top. With one, 宀 is a roof (家).",
          forms=[F("冖", TOP, host="写", name=N("秃宝盖", "tū bǎo gài"))]),
    15: R("ice", "bīng", about="Ice and cold",
          note="Two dots is ice; three dots, 氵, is water: 冷 cold · 河 river.",
          forms=[
              F("冫", LEFT, host="冷", name=N("两点水", "liǎng diǎn shuǐ"),
                tip="A dot, then a stroke rising to the right"),
              F("⺀", BOTTOM, host="冬", tip="The same two dots, underneath", ex="冬寒"),
          ]),
    16: R("small table", "jī"),
    17: R("open box", "kǎn", name=N("凶字框", "xiōng zì kuàng")),
    18: R("knife", "dāo", about="Knives and cutting",
          note="刂 knife sits on the right (到 别); 力 strength (动 办) is another shape.",
          forms=[
              F("刂", RIGHT, host="到", name=N("立刀旁", "lì dāo páng"),
                tip="Two uprights: a short one, then a long one with a hook"),
              F("刀"),
              F("⺈", TOP, host="负", name=N("刀字头", "dāo zì tóu"),
                tip="Squeezed onto the top, where it no longer means knife", ex="色负争免危"),
          ]),
    19: R("strength", "lì", about="Strength and effort", name=N("力字旁", "lì zì páng"),
          note="In 力 the slash pokes through the top; in 刀 knife it doesn't."),
    20: R("wrap", "bāo", about="Wrapping round",
          forms=[F("勹", TOP_RIGHT, host="包", name=N("包字头", "bāo zì tóu"))]),
    21: R("spoon; dagger", "bǐ"),
    22: R("box", "fāng", name=N("三框儿", "sān kuàng r"),
          note="匚 and 匸 are almost the same shape, and modern print draws both as 匚."),
    23: R("hiding place", "xì",
          note="匸 and 匚 are almost the same shape, and modern print draws both as 匚."),
    24: R("ten", "shí"),
    25: R("divination", "bǔ", about="Fortune-telling: a crack in a heated shell",
          forms=[F("卜"), F("⺊", TOP, host="占")]),
    26: R("kneeling person; seal", "jié",
          note="卩 is a square hook (印 即); 阝 (院 部) curls like an ear.",
          forms=[
              F("卩", RIGHT, host="印", name=N("单耳旁", "dān ěr páng")),
              F("㔾", BOTTOM, host="危"),
          ]),
    27: R("cliff", "hǎn", about="An overhanging cliff, and shelters",
          note="厂 has no dot; 广 (店) has one; 疒 (病) adds two more strokes.",
          forms=[F("厂", TOP_LEFT, host="历", name=N("厂字旁", "chǎng zì páng"),
                   tip="On its own 厂 is chǎng, a factory")]),
    28: R("private", "sī", name=N("私字儿", "sī zì r")),
    29: R("again; a right hand", "yòu", about="A hand: it began as a picture of one",
          name=N("又字旁", "yòu zì páng")),
    30: R("mouth", "kǒu", about="The mouth: eating, speaking, sounds",
          name=N("口字旁", "kǒu zì páng"),
          note="口 sits beside or above other parts (吃 号); 囗 goes all the way round them (国 回)."),
    31: R("enclosure", "wéi", about="Enclosures and borders",
          note="囗 goes all the way round (国 回); 口 mouth sits beside the other parts (吃).",
          forms=[F("囗", AROUND, host="国", name=N("国字框", "guó zì kuàng"))]),
    32: R("earth", "tǔ", about="Earth, ground and places",
          note="土 earth: the lower stroke is longer. 士 scholar: the upper one is.",
          forms=[
              F("土", LEFT, host="地", name=N("提土旁", "tí tǔ páng"),
                tip="The last stroke rises to the right instead of lying flat"),
              F("土"),
          ]),
    33: R("scholar; soldier", "shì",
          note="士 scholar: the upper stroke is longer. 土 earth: the lower one is."),
    34: R("go", "zhǐ",
          note="夂 has three strokes and sits on top (备 冬); 攵 has four and sits on the right (放).",
          forms=[F("夂", TOP, host="备", name=N("折文", "zhé wén"))]),
    35: R("go slowly", "suī", note="Drawn almost exactly like 夂."),
    36: R("evening", "xī", about="Evening and night", name=N("夕字旁", "xī zì páng")),
    37: R("big", "dà", about="A person standing with arms spread wide",
          name=N("大字头", "dà zì tóu"),
          note="犬 dog adds a dot at the top right; 太 too adds one underneath."),
    38: R("woman", "nǚ", about="Women and family", forms=[
        F("女", LEFT, host="好", name=N("女字旁", "nǚ zì páng"),
          tip="Narrower, and the flat stroke becomes a rising tick"),
        F("女", BOTTOM, host="要", name=N("女字底", "nǚ zì dǐ"), ex="要安委妻"),
    ]),
    39: R("child", "zǐ", about="Children", forms=[
        F("子", LEFT, host="孩", name=N("子字旁", "zǐ zì páng"),
          tip="The flat stroke becomes a rising tick"),
        F("子"),
    ]),
    40: R("roof", "mián", about="A roof: houses, rooms, keeping safe",
          note="宀 roof has a dot on top; 冖 cover (写) has none; 穴 cave (空) adds 八 below.",
          forms=[F("宀", TOP, host="家", name=N("宝盖头", "bǎo gài tóu"))]),
    41: R("inch; a hand", "cùn", about="A hand, and measuring", name=N("寸字旁", "cùn zì páng")),
    42: R("small", "xiǎo", forms=[
        F("小"),
        F("⺌", TOP, host="当", name=N("小字头", "xiǎo zì tóu"),
          tip="The hook goes, and the side strokes lean in", ex="当常尚光"),
    ]),
    43: R("lame", "wāng"),
    44: R("body; shelter", "shī", about="A body lying down, or a roof and a wall",
          note="尸 has no dot on top; 户 door (房) has one.",
          forms=[F("尸", TOP_LEFT, host="层", name=N("尸字头", "shī zì tóu"))]),
    45: R("sprout", "chè"),
    46: R("mountain", "shān", about="Mountains and hills", name=N("山字旁", "shān zì páng")),
    47: R("river", "chuān", r="川"),
    48: R("work", "gōng", about="Tools and work", name=N("工字旁", "gōng zì páng")),
    49: R("self", "jǐ", ex="已巴",
          note="己 is open at the top left; 已 closes halfway; 巳 closes completely."),
    50: R("cloth", "jīn", about="Cloth, and things made of it", name=N("巾字旁", "jīn zì páng"),
          note="币 money is 巾 with a slash on top."),
    51: R("dry; shield", "gān",
          note="干 is flat on top; 千 thousand starts with a slash; 于 ends in a hook."),
    52: R("tiny", "yāo"),
    53: R("building", "guǎng", about="A building open on one side",
          note="广 has a dot on top; 厂 (厅) has none; 疒 (病) adds two strokes.",
          forms=[F("广", TOP_LEFT, host="店", name=N("广字旁", "guǎng zì páng"),
                   tip="On its own 广 means wide")]),
    54: R("long stride", "yǐn", note="廴 has no dot; 辶 (这) has one.",
          forms=[F("廴", BOTTOM_LEFT, host="建", name=N("建之旁", "jiàn zhī páng"))]),
    55: R("two hands", "gǒng"),
    56: R("arrow on a cord", "yì", note="弋 has no slash at the bottom; 戈 spear (我) does."),
    57: R("bow", "gōng", about="Bows: stretching and bending",
          forms=[F("弓", LEFT, host="张", name=N("弓字旁", "gōng zì páng"))]),
    58: R("snout", "jì"),
    59: R("hair; stripes", "shān", about="Hair, brushstrokes and patterns",
          forms=[F("彡", RIGHT, host="影", name=N("三撇儿", "sān piě r"))]),
    60: R("step", "chì", about="Roads and walking",
          note="Two slashes and an upright. 亻 person (你) has only one slash.",
          forms=[F("彳", LEFT, host="往", name=N("双人旁", "shuāng rén páng"))]),
    61: R("heart", "xīn", word="心", about="The heart and mind: feelings and thoughts",
          note="忄 and 心 are one radical: 忙 busy and 忘 forget are the same 亡 with the heart moved.",
          forms=[
              F("忄", LEFT, host="快", name=N("竖心旁", "shù xīn páng"),
                tip="The heart stood upright to fit on the left"),
              F("心", BOTTOM, host="想", name=N("心字底", "xīn zì dǐ"),
                tip="Flat and wide underneath"),
              F("⺗", BOTTOM, host="恭",
                tip="A rarer form underneath: worth recognising more than writing"),
          ]),
    62: R("spear", "gē", about="Weapons and fighting", name=N("戈字旁", "gē zì páng"),
          note="戈 has a slash across the bottom; 弋 (式) doesn't."),
    63: R("door", "hù", about="Doors and houses",
          note="户 has a dot on top; 尸 body (层) doesn't.",
          forms=[F("户", TOP_LEFT, host="房", name=N("户字头", "hù zì tóu"))]),
    64: R("hand", "shǒu", word="手", about="Things done with the hands", forms=[
        F("扌", LEFT, host="打", name=N("提手旁", "tí shǒu páng"),
          tip="Across, a hooked upright, then a rising tick"),
        F("手", BOTTOM, host="拿", name=N("手字底", "shǒu zì dǐ")),
    ]),
    65: R("branch; support", "zhī"),
    66: R("tap, strike", "pū", word="攴", about="Actions, often done with force",
          note="攵 has four strokes and sits on the right (放); 夂 has three and sits on top (备).",
          forms=[F("攵", RIGHT, host="放", name=N("反文旁", "fǎn wén páng"))]),
    67: R("writing; pattern", "wén"),
    68: R("dipper", "dǒu"),
    69: R("axe", "jīn", about="An axe, and cutting", name=N("斤字旁", "jīn zì páng")),
    70: R("square; flag", "fāng", about="Banners and flags", name=N("方字旁", "fāng zì páng")),
    71: R("without", "wú"),
    72: R("sun", "rì", about="The sun, light and time", name=N("日字旁", "rì zì páng"),
          note="日 sun is tall; 曰 say (最 曾) is wider and flatter."),
    73: R("say", "yuē", note="曰 say is wide and flat; 日 sun is tall."),
    74: R("moon", "yuè", about="The moon, and time", name=N("月字旁", "yuè zì páng"),
          note="Body words (脑 脸 腿) use ⺼ flesh, drawn exactly like 月: that is radical 130."),
    75: R("tree", "mù", about="Trees and wood", note="禾 grain (科) is 木 with a slash on top.",
          forms=[
              F("木", LEFT, host="校", name=N("木字旁", "mù zì páng"),
                tip="The last stroke shrinks to a dot, clear of the right-hand part"),
              F("木"),
          ]),
    76: R("yawn; open mouth", "qiàn", about="A mouth open wide: breathing, singing",
          forms=[F("欠", RIGHT, host="歌", name=N("欠字旁", "qiàn zì páng"))]),
    77: R("stop; foot", "zhǐ", about="A foot, and stopping", name=N("止字旁", "zhǐ zì páng")),
    78: R("death", "dǎi", about="Death and decay", name=N("歹字旁", "dǎi zì páng")),
    79: R("strike", "shū", about="Striking with a weapon or tool",
          forms=[F("殳", RIGHT, host="段", name=N("殳字旁", "shū zì páng"))]),
    80: R("mother", "mǔ", r="母",
          note="The Kangxi radical is 毋 wú, 'do not': one stroke through the middle where 母 has two dots."),
    81: R("compare", "bǐ"),
    82: R("fur, hair", "máo"),
    83: R("clan", "shì", note="民 people is 氏 with the top closed."),
    84: R("air, gas", "qì", about="Gases and air", name=N("气字头", "qì zì tóu")),
    85: R("water", "shuǐ", word="水", about="Water and liquids",
          note="Three dots is water; two dots, 冫, is ice: 河 river · 冷 cold.",
          forms=[
              F("氵", LEFT, host="河", name=N("三点水", "sān diǎn shuǐ"),
                tip="Three dots, the last one rising to the right"),
              F("水", BOTTOM, host="泉", name=N("水字底", "shuǐ zì dǐ")),
              F("氺", BOTTOM, host="泰",
                tip="A hooked upright in the middle, short strokes either side", ex="求泰录"),
          ]),
    86: R("fire", "huǒ", about="Fire, heat and cooking",
          note="Four dots underneath is fire (点 热), not water.",
          forms=[
              F("火", LEFT, host="灯", name=N("火字旁", "huǒ zì páng"),
                tip="The last stroke shrinks to a dot"),
              F("灬", BOTTOM, host="点", name=N("四点底", "sì diǎn dǐ"),
                tip="Fire underneath, drawn as four dots"),
              F("火"),
          ]),
    87: R("claw", "zhǎo", about="A hand reaching down from above", forms=[
        F("爫", TOP, host="爱", name=N("爪字头", "zhǎo zì tóu"), ex="爱采受"),
        F("爪"),
    ]),
    88: R("father", "fù", about="Fathers and grandfathers",
          forms=[F("父", TOP, host="爸", name=N("父字头", "fù zì tóu"))]),
    89: R("crossed lines", "yáo"),
    90: R("split wood", "qiáng", word="爿",
          note="丬 has an upright stroke; 冫 ice (冷) is only two dots.",
          forms=[F("丬", LEFT, host="将", name=N("将字旁", "jiāng zì páng"), ex="将状")]),
    91: R("slice", "piàn", name=N("片字旁", "piàn zì páng")),
    92: R("tooth", "yá", ex="穿呀芽"),
    93: R("ox, cow", "niú", about="Cattle", note="牛 pokes through the top; 午 noon doesn't.",
          forms=[
              F("牜", LEFT, host="物", part="牛", name=N("牛字旁", "niú zì páng"),
                tip="The last flat stroke becomes a rising tick"),
              F("牛"),
          ]),
    94: R("dog", "quǎn", about="Animals, originally dogs",
          note="Don't mix 犭 up with 彳 (往) or 亻 (你).",
          forms=[
              F("犭", LEFT, host="狗", name=N("反犬旁", "fǎn quǎn páng"),
                tip="A slash, a curving hook, then another slash"),
              F("犬", ex="哭状献"),
          ]),
    95: R("dark, deep", "xuán"),
    96: R("jade", "yù", about="Jade and precious things",
          note="On the left 王 means jade, not king: 玩 play · 现 appear · 球 ball.",
          forms=[
              F("王", LEFT, host="玩", name=N("王字旁", "wáng zì páng"),
                tip="Written like 王 king, with the last stroke rising"),
              F("玉", ex="宝国"),
          ]),
    97: R("melon", "guā"),
    98: R("tile, pottery", "wǎ", about="Fired clay"),
    99: R("sweet", "gān"),
    100: R("life; grow", "shēng", ex="星性姓"),
    101: R("use", "yòng"),
    102: R("field", "tián", about="Fields and farming", name=N("田字旁", "tián zì páng"),
           note="田 is closed; the upright pokes out the top in 由, the bottom in 甲, both ends in 申."),
    103: R("bolt of cloth", "pǐ"),
    104: R("sickness", "nè", about="Illness and pain",
           forms=[F("疒", TOP_LEFT, host="病", name=N("病字旁", "bìng zì páng"),
                    tip="广 with a dot and a rising stroke added on the left")]),
    105: R("footsteps", "bō", forms=[F("癶", TOP, host="登", name=N("登字头", "dēng zì tóu"))]),
    106: R("white", "bái", note="白 is 日 with a slash on top; 自 self is 目 with one."),
    107: R("skin", "pí", name=N("皮字旁", "pí zì páng")),
    108: R("dish", "mǐn", about="Dishes and containers", note="血 blood is 皿 with a slash on top.",
           forms=[F("皿", BOTTOM, host="盘", name=N("皿字底", "mǐn zì dǐ"))]),
    109: R("eye", "mù", about="The eye, and looking", name=N("目字旁", "mù zì páng"),
           note="目 eye has two strokes inside; 日 sun has one."),
    110: R("spear", "máo"),
    111: R("arrow", "shǐ", note="In 矢 nothing pokes through the top; in 失 lose, the slash does.",
           forms=[F("矢", LEFT, host="知", name=N("矢字旁", "shǐ zì páng"),
                    tip="The last stroke shrinks to a dot")]),
    112: R("stone", "shí", about="Stones and minerals",
           note="石 starts with the flat stroke; 右 right starts with the slash.",
           forms=[F("石", LEFT, host="破", name=N("石字旁", "shí zì páng"))]),
    113: R("altar; spirits", "shì", word="示", about="Gods, rituals and blessings",
           note="One dot, 礻, is spirits (礼 神); two dots, 衤, is clothing (衬 被).",
           forms=[
               F("礻", LEFT, host="礼", name=N("示字旁", "shì zì páng"),
                 tip="Ends in a single short stroke"),
               F("示", BOTTOM, host="票", name=N("示字底", "shì zì dǐ")),
           ]),
    114: R("track", "róu"),
    115: R("grain", "hé", about="Grain and crops",
           note="禾 is 木 tree with a drooping head: one extra slash on top.",
           forms=[F("禾", LEFT, host="科", name=N("禾木旁", "hé mù páng"),
                    tip="The last stroke shrinks to a dot")]),
    116: R("cave, hole", "xué", about="Caves and holes",
           forms=[F("穴", TOP, host="空", name=N("穴宝盖", "xué bǎo gài"))]),
    117: R("stand", "lì", forms=[
        F("立", LEFT, host="站", name=N("立字旁", "lì zì páng"),
          tip="The last stroke rises to the right"),
        F("立"),
    ]),
    118: R("bamboo", "zhú", about="Bamboo, and things made of it",
           note="⺮ bamboo has six strokes (笑 笔); 艹 grass has three (花 草).",
           forms=[
               F("⺮", TOP, host="笑", name=N("竹字头", "zhú zì tóu"),
                 tip="Two short halves side by side, each ending in a dot"),
               F("竹"),
           ]),
    119: R("rice", "mǐ", about="Rice and grain", forms=[
        F("米", LEFT, host="糖", name=N("米字旁", "mǐ zì páng"),
          tip="The last stroke shrinks to a dot"),
        F("米"),
    ]),
    120: R("silk, thread", "mì", word="糸", about="Thread and cloth, and tying together",
           forms=[
               F("纟", LEFT, host="给", name=N("绞丝旁", "jiǎo sī páng"),
                 tip="Two twists and a rising tick"),
               F("糸", BOTTOM, host="紧", name=N("绞丝底", "jiǎo sī dǐ")),
           ]),
    121: R("jar", "fǒu", forms=[F("缶", LEFT, host="缺", name=N("缶字旁", "fǒu zì páng"))]),
    122: R("net", "wǎng", about="Nets and catching",
           note="罒 on top is a net (罗 置), not the number 四.",
           forms=[
               F("罒", TOP, host="罗", name=N("四字头", "sì zì tóu"), tip="Flattened onto the top"),
               F("网"),
           ]),
    123: R("sheep", "yáng", about="Sheep, and good things", forms=[
        F("𦍌", TOP, host="美", part="羊", name=N("羊字头", "yáng zì tóu"),
          tip="The upright stops short instead of running through", ex="美着差羔"),
        F("羊"),
    ]),
    124: R("feather", "yǔ", about="Feathers and wings", name=N("羽字旁", "yǔ zì páng")),
    125: R("old", "lǎo", forms=[
        F("耂", TOP_LEFT, host="考", name=N("老字头", "lǎo zì tóu")),
        F("老"),
    ]),
    126: R("and; beard", "ér"),
    127: R("plough", "lěi", name=N("耒字旁", "lěi zì páng")),
    128: R("ear", "ěr", about="Ears and hearing", forms=[
        F("耳", LEFT, host="联", name=N("耳字旁", "ěr zì páng"),
          tip="The last stroke rises to the right"),
        F("耳"),
    ]),
    129: R("brush", "yù"),
    130: R("meat, flesh", "ròu", about="The body and its parts",
           note="⺼ looks exactly like 月: 脑 brain and 腿 leg are body words; 朋 friend and 期 period are not.",
           forms=[
               F("⺼", LEFT, host="脑", name=N("肉月旁", "ròu yuè páng"),
                 tip="Written like 月 moon, narrow, on the left"),
               F("⺼", BOTTOM, host="背", tip="The same 月 shape, full width underneath"),
               F("肉"),
           ]),
    131: R("minister", "chén"),
    132: R("self; nose", "zì", note="自 is 目 with a slash on top; 白 white is 日 with one."),
    133: R("arrive", "zhì"),
    134: R("mortar", "jiù"),
    135: R("tongue", "shé", name=N("舌字旁", "shé zì páng")),
    136: R("opposed feet", "chuǎn"),
    137: R("boat", "zhōu", about="Boats and ships",
           forms=[F("舟", LEFT, host="船", name=N("舟字旁", "zhōu zì páng"),
                    tip="The flat stroke becomes a rising tick")]),
    138: R("stubborn", "gèn"),
    139: R("colour", "sè"),
    140: R("grass", "cǎo", word="艸", about="Grass, plants and flowers",
           note="艹 grass has three strokes (花 草); ⺮ bamboo has six (笑).",
           forms=[F("艹", TOP, host="花", name=N("草字头", "cǎo zì tóu"),
                    tip="A flat stroke, then two short uprights")]),
    141: R("tiger", "hū", about="Tigers",
           forms=[F("虍", TOP_LEFT, host="虚", name=N("虎字头", "hǔ zì tóu"))]),
    142: R("insect", "chóng", about="Insects, worms and snakes", name=N("虫字旁", "chóng zì páng")),
    143: R("blood", "xuè", note="血 blood is 皿 dish with a slash on top."),
    144: R("walk; crossroads", "xíng", about="Crossroads and walking"),
    145: R("clothing", "yī", word="衣", about="Clothes and cloth",
           note="Two dots, 衤, is clothing (衬 被); one dot, 礻, is spirits (礼 神).",
           forms=[
               F("衤", LEFT, host="衬", name=N("衣字旁", "yī zì páng"),
                 tip="Ends in two short strokes"),
               F("衣", BOTTOM, host="装", name=N("衣字底", "yī zì dǐ")),
           ]),
    146: R("cover", "xī",
           note="The Kangxi radical is 襾 yà, a cover; today it is written like 西 xī, west.",
           forms=[
               F("覀", TOP, host="要", name=N("西字头", "xī zì tóu"),
                 tip="西 with its legs straightened"),
               F("西"),
           ]),
    147: R("see", "jiàn", r="见", about="Seeing", name=N("见字旁", "jiàn zì páng"),
           note="见 ends in a curling hook; 贝 shell ends in a dot."),
    148: R("horn", "jiǎo", name=N("角字旁", "jiǎo zì páng")),
    149: R("speech", "yán", about="Speech and language", forms=[
        F("讠", LEFT, host="说", name=N("言字旁", "yán zì páng"),
          tip="Just two strokes: a dot, and a bend that rises"),
        F("言"),
    ]),
    150: R("valley", "gǔ"),
    151: R("bean", "dòu"),
    152: R("pig", "shǐ"),
    153: R("cat-like beast", "zhì", name=N("豸字旁", "zhì zì páng")),
    154: R("shell; money", "bèi", r="贝", about="Money and value: shells were once money",
           name=N("贝字旁", "bèi zì páng"), note="贝 ends in a dot; 见 see ends in a curling hook."),
    155: R("red", "chì"),
    156: R("walk", "zǒu", about="Walking and running", forms=[
        F("走", BOTTOM_LEFT, host="起", name=N("走字旁", "zǒu zì páng"),
          tip="The last stroke sweeps along under the right-hand part"),
        F("走"),
    ]),
    157: R("foot", "zú", about="Feet, and moving them", forms=[
        F("⻊", LEFT, host="跑", part="足", name=N("足字旁", "zú zì páng"),
          tip="The bottom becomes an upright and a rising tick"),
        F("足"),
    ]),
    158: R("body", "shēn", forms=[
        F("身", LEFT, host="躺", name=N("身字旁", "shēn zì páng")),
        F("身"),
    ]),
    159: R("cart", "chē", about="Vehicles and wheels", forms=[
        F("车", LEFT, host="轻", name=N("车字旁", "chē zì páng"),
          tip="The last stroke rises to the right"),
        F("车"),
    ]),
    160: R("bitter", "xīn", about="Bitterness and hardship"),
    161: R("early morning", "chén"),
    162: R("walk", "chuò", word="辵", about="Movement: going, coming, passing",
           note="辶 has a dot on top; 廴 (建) doesn't.",
           forms=[F("辶", BOTTOM_LEFT, host="这", name=N("走之底", "zǒu zhī dǐ"),
                    tip="Written last, sweeping under the rest of the character")]),
    163: R("city", "yì", word="邑", about="Places, towns and districts",
           note="On the left the same 阝 is another radical: 阜, a hill (院 阳).",
           forms=[F("阝", RIGHT, host="部", name=N("右耳旁", "yòu ěr páng"),
                    tip="On the right, 阝 is 邑: a city")]),
    164: R("wine jar", "yǒu", about="Wine and fermentation",
           forms=[F("酉", LEFT, host="配", name=N("酉字旁", "yǒu zì páng"))]),
    165: R("distinguish", "biàn", note="釆 has a slash on top; 米 rice doesn't."),
    166: R("village", "lǐ"),
    167: R("metal, gold", "jīn", about="Metals, tools and money", forms=[
        F("钅", LEFT, host="钱", name=N("金字旁", "jīn zì páng"),
          tip="Five strokes, the last an upright that rises"),
        F("金"),
    ]),
    168: R("long", "cháng", r="长"),
    169: R("gate", "mén", r="门", about="Gates and doors", name=N("门字框", "mén zì kuàng")),
    170: R("mound, hill", "fù", word="阜", about="Hills, slopes and walls",
           note="On the right the same 阝 is another radical: 邑, a city (都 部).",
           forms=[F("阝", LEFT, host="院", name=N("左耳旁", "zuǒ ěr páng"),
                    tip="On the left, 阝 is 阜: a hill")]),
    171: R("reach", "lì"),
    172: R("short-tailed bird", "zhuī", about="Birds", name=N("隹字旁", "zhuī zì páng")),
    173: R("rain", "yǔ", about="Rain and weather", forms=[
        F("⻗", TOP, host="雪", part="雨", name=N("雨字头", "yǔ zì tóu"),
          tip="Flattened onto the top, with the dots shrunk"),
        F("雨"),
    ]),
    174: R("blue-green", "qīng"),
    175: R("not; wrong", "fēi"),
    176: R("face", "miàn"),
    177: R("leather", "gé", about="Leather and hide",
           forms=[F("革", LEFT, host="鞋", name=N("革字旁", "gé zì páng"))]),
    178: R("tanned leather", "wéi", r="韦"),
    179: R("leek", "jiǔ"),
    180: R("sound", "yīn", name=N("音字旁", "yīn zì páng")),
    181: R("head", "yè", about="The head and face",
           forms=[F("页", RIGHT, host="顺", name=N("页字旁", "yè zì páng"),
                    tip="It meant a head first; 'page' came later")]),
    182: R("wind", "fēng", r="风"),
    183: R("fly", "fēi", r="飞"),
    184: R("food, eat", "shí", about="Food and eating", forms=[
        F("饣", LEFT, host="饭", name=N("食字旁", "shí zì páng"),
          tip="Three strokes: a slash, a bend, and an upright that rises"),
        F("食"),
    ]),
    185: R("head", "shǒu"),
    186: R("fragrant", "xiāng"),
    187: R("horse", "mǎ", about="Horses and riding", forms=[
        F("马", LEFT, host="骑", name=N("马字旁", "mǎ zì páng"),
          tip="The last stroke rises to the right"),
        F("马"),
    ]),
    188: R("bone", "gǔ", name=N("骨字旁", "gǔ zì páng")),
    189: R("tall", "gāo"),
    190: R("long hair", "biāo"),
    191: R("fight", "dòu", note="Simplified Chinese writes it 斗."),
    192: R("sacrificial wine", "chàng"),
    193: R("cauldron", "lì"),
    194: R("ghost", "guǐ", about="Ghosts and spirits", name=N("鬼字旁", "guǐ zì páng")),
    195: R("fish", "yú", about="Fish", forms=[
        F("鱼", LEFT, host="鲜", name=N("鱼字旁", "yú zì páng"),
          tip="The last stroke rises to the right"),
        F("鱼"),
    ]),
    196: R("bird", "niǎo", about="Birds", note="鸟 bird has a dot for its eye; 乌 crow has none.",
           forms=[F("鸟", RIGHT, host="鸡", name=N("鸟字旁", "niǎo zì páng"))]),
    197: R("salt", "lǔ", r="卤"),
    198: R("deer", "lù"),
    199: R("wheat", "mài", r="麦"),
    200: R("hemp; numb", "má"),
    201: R("yellow", "huáng", r="黄"),
    202: R("millet", "shǔ"),
    203: R("black", "hēi", name=N("黑字旁", "hēi zì páng")),
    204: R("embroidery", "zhǐ"),
    205: R("frog", "mǐn", r="黾"),
    206: R("tripod cauldron", "dǐng"),
    207: R("drum", "gǔ"),
    208: R("rat, mouse", "shǔ"),
    209: R("nose", "bí"),
    210: R("even", "qí", r="齐"),
    211: R("teeth", "chǐ", r="齿", name=N("齿字旁", "chǐ zì páng")),
    212: R("dragon", "lóng", r="龙"),
    213: R("turtle", "guī", r="龟"),
    214: R("flute", "yuè"),
}


# Example glosses where no dictionary's first sense reads right on a worksheet.
# The function words first — 是 opens with "indeed", 的 with "possessive,
# adjectival suffix" — then the characters whose everyday meaning comes a few
# senses down: 关 is "mountain pass" before it is "to close", 穿 "to bore
# through" before "to wear".
EXAMPLE_GLOSS: dict[str, str] = {
    # function words
    "的": "of; 's",
    "了": "(finished)",
    "是": "to be",
    "们": "(plural)",
    "吗": "(question)",
    "呢": "(question)",
    "吧": "(suggestion)",
    "这": "this",
    "那": "that",
    "都": "all; both",
    "还": "still; also",
    "过": "to pass",
    "着": "(ongoing)",
    "得": "to get",
    "很": "very",
    "也": "also",
    "就": "then; just",
    "么": "(in 什么)",
    "会": "can; to meet",
    "和": "and",
    "在": "at; in",
    "有": "to have",
    "对": "correct; towards",
    "要": "to want",
    "把": "to hold",
    "被": "quilt; (passive)",
    "从": "from",
    "比": "to compare",
    "个": "(measure word)",
    "些": "some",
    "其": "its; that",
    "之": "of",
    "乎": "(in 几乎)",
    "于": "at; in",
    "所": "place",
    "而": "and; but",
    "为": "for; to be",
    "才": "only then",
    "第": "(ordinal prefix)",
    "什": "what (in 什么)",
    "他": "he",
    "您": "you (polite)",
    "张": "sheet; (measure word)",
    "条": "strip; (measure word)",
    "本": "root; (measure word)",
    "辆": "(measure: vehicles)",
    "艘": "(measure: ships)",
    # the everyday sense is not the first one
    "想": "to think; to want",
    "息": "breath; rest",
    "机": "machine",
    "今": "now; today",
    "介": "between",
    "经": "to pass through",
    "提": "to lift; to mention",
    "录": "to record",
    "样": "kind; look",
    "查": "to check",
    "节": "festival; section",
    "药": "medicine",
    "绍": "(in 介绍) introduce",
    "话": "words; speech",
    "育": "to raise; to educate",
    "然": "so; like that",
    "场": "place; field",
    "销": "to sell",
    "别": "don't; other",
    "阳": "sun",
    "跟": "with; to follow",
    "预": "in advance",
    "衬": "lining; shirt",
    "表": "surface; a watch",
    "装": "to pack; to dress",
    "布": "cloth",
    "属": "to belong to",
    "穿": "to wear",
    "理": "reason; to tidy",
    "共": "together",
    "关": "to close; to concern",
    "祝": "to wish",
    "原": "original",
    "克": "gram; to overcome",
    "联": "to join",
    "聪": "clever",
    "次": "time (occurrence)",
    "辣": "spicy",
    "占": "to occupy",
    "题": "topic; question",
    "照": "to shine; photo",
    "进": "to enter",
    "道": "road; way",
    "兴": "to rise; interest",
    "乱": "messy",
    "意": "idea; meaning",
    "记": "to remember",
    "请": "please; to invite",
    "警": "police",
    "脏": "dirty",
    "城": "city",
    "晚": "evening; late",
    "利": "benefit; sharp",
    "负": "to bear; to lose",
    "争": "to argue; compete",
    "资": "funds",
    "院": "courtyard",
    "称": "to call; to weigh",
    "种": "kind; to plant",
    "研": "to research",
    "套": "set; to cover",
    "顺": "smooth; along",
    "颜": "colour; face",
    "带": "to bring; belt",
    "常": "often",
    "努": "to strive",
    "展": "to spread out",
    "待": "to wait; to treat",
    "馆": "hall; restaurant",
    "饱": "full (from eating)",
    "输": "to lose",
    "驻": "to be stationed",
    "典": "standard; classic",
    "醉": "drunk",
    "礼": "gift; courtesy",
    "元": "yuan; first",
    "华": "China; splendid",
    "起": "to rise; to start",
    "罗": "net",
    "卷": "to roll; volume",
    "觉": "to feel",
    "主": "main; owner",
    "房": "house; room",
    "竟": "unexpectedly",
    "当": "to act as; ought",
    "尚": "still; to esteem",
    "封": "to seal; envelope",
    "曾": "once; ever",
    "即": "that is; at once",
    "却": "but; yet",
    "差": "poor; to differ",
    "正": "straight; just",
    "影": "shadow; film",
    "弄": "to do; to fiddle",
    "舍": "house; to give up",
    "并": "and; to combine",
    "受": "to receive",
    "冒": "to emit; to risk",
    "处": "place; to deal with",
    "解": "to explain; to untie",
    "象": "elephant; image",
    "牌": "sign; brand",
    "性": "nature; sex",
    "将": "will; to lead",
    "状": "state; form",
    "朝": "towards; dynasty",
    "服": "clothes; to serve",
    "望": "to hope; to gaze",
    "端": "end; to carry",
    "打": "to hit",
    "汉": "Han Chinese",
    "后": "after; behind",
    "同": "same",
    "英": "hero; English",
    "科": "subject; science",
    "快": "fast",
    "没": "not have",
    "找": "to look for",
    "听": "to listen",
    "作": "to do; to make",
    "体": "body",
    "点": "dot; a bit",
    "能": "can; ability",
    "定": "to fix; certain",
    "准": "accurate; to allow",
    "故": "reason; old",
    "领": "collar; to lead",
    "般": "sort; kind",
    "亲": "close; parent",
    "义": "meaning; justice",
    "市": "market; city",
    "间": "between; room",
    "闻": "to hear; news",
    "现": "now; to appear",
    "由": "from; cause",
    "申": "to state",
    "精": "essence; fine",
    "部": "part; department",
    "图": "picture; map",
    "露": "dew; to reveal",
    "神": "god; spirit",
    "站": "to stand; a station",
    "奶": "milk; grandma",
    "脏": "internal organ",
    "背": "the back",
    "企": "enterprise",
    "余": "surplus",
    "肖": "to resemble",
    "腐": "rotten",
    "泰": "peaceful",
    "渴": "thirsty",
}

# Characters that are true to the data but no use as an example: a surname
# (冯), a variant nobody writes (聋), a classical particle (矣), manure (粪).
EXAMPLE_REJECT = set("冯聋矣粪粤鲁叁贰毓氅觯觥")


def shape_glosses(is_character) -> dict[str, str]:
    """
    Meanings for the component shapes that are only ever parts of characters.

    The character sheets gloss every part they list, and for a shape like 氵 or
    扌 the only sensible gloss is the radical's meaning. A shape that is also a
    character in its own right (心, 贝, 户) keeps its own dictionary sense —
    applying the radical's there is exactly how 心 came to be glossed "eight".
    """
    seen: dict[str, list[str]] = {}
    for spec in RADICALS.values():
        glyphs = [f["g"] for f in spec["forms"]] if spec["forms"] else [spec["r"]]
        for g in glyphs:
            if not g or is_character(g):
                continue
            meanings = seen.setdefault(g, [])
            if spec["mean"] not in meanings:
                meanings.append(spec["mean"])
    # 阝 is two radicals: 阜 hill on the left, 邑 city on the right. The sheets
    # know which side a part sits on and say which; the table just has both.
    return {g: " · ".join(m) for g, m in seen.items()}
