import type { ScreenId } from './types';

/**
 * The kit's own Chinese, in one place: the screens use these names rather
 * than literals, so the glossary test sees every string the chrome can show.
 */
export const S = {
  miniProgram: '小程序',
  practice: '练习模式',
  tabHome: '首页',
  tabMenu: '点单',
  tabCart: '购物车',
  tabOrders: '订单',
  tabMe: '我的',
  noOrders: '暂无订单',
  spec: '选规格',
  deal: '预估到手',
  sold: '月售',
  emptyCart: '未选购商品',
  checkout: '去结算',
  added: '已加入购物车',
  choose: '请选择',
  addToCart: '加入购物车',
  buyNow: '立即购买',
  clearCart: '清空购物车',
  chosenItems: '已选商品',
  confirm: '确认订单',
  pickup: '自提',
  delivery: '外送',
  deliverySoon: '外送即将开放',
  store: '取餐门店',
  expect: '预计',
  ready: '可取',
  dine: '取餐方式',
  eatIn: '堂食',
  takeAway: '外带',
  coupon: '优惠券',
  sheets: '张',
  chosen: '已选',
  usable: '可用',
  unusable: '不可用',
  noCoupon: '不使用优惠券',
  chooseCoupon: '选择优惠券',
  note: '备注',
  taste: '口味偏好',
  other: '其他要求',
  none: '无',
  ok: '确定',
  payMethod: '支付方式',
  wechatPay: '微信支付',
  itemsTotal: '商品金额',
  total: '合计',
  saved: '已优惠',
  pay: '去支付',
  inAll: '共',
  pieces: '件',
  wallet: '零钱',
  pin: '输入支付密码',
  paid: '支付成功',
  done: '完成',
  code: '取餐码',
  ordered: '已下单',
  making: '制作中',
  collect: '请取餐',
  minutes: '分钟后可取',
  details: '订单详情',
  orderTime: '下单时间',
  paidAmount: '实付',
  wrong: '不对哦',
  fine: '好的',
  askCode: '取餐码是多少',
  askTotal: '一共多少钱',
  askTime: '几点可以取',
  askSaved: '优惠了多少',
  tapIt: '点一下',
  right: '对',
  lookAgain: '再看看',
  near: '距您',
  pickupHere: '到店取',
  skipQueue: '下单免排队',
  toYou: '送到你身边',
  member: '会员',
  newOnes: '新品推荐',
  onlyIced: '仅冰饮',
  // counter shops (先付后吃)
  orderHere: '到店点餐',
  queueCode: '取餐号',
  listen: '请留意叫号',
  // table service (扫码点餐, 先吃后付)
  scanOrder: '扫码点餐',
  tableNo: '桌号',
  diners: '就餐人数',
  people: '人',
  chooseTea: '选茶',
  start: '开始点餐',
  perHead: '位',
  chosenDone: '选好了',
  confirmOrder: '确认下单',
  placeOrder: '下单',
  placed: '下单成功',
  cooking: '菜品正在准备中',
  orderedDishes: '已点菜品',
  more: '加菜',
  callWaiter: '呼叫服务员',
  waiterCalled: '已通知服务员',
  hurry: '催单',
  hurried: '已催单',
  toBill: '去买单',
  bill: '买单',
  dishes: '菜品',
  billPaid: '买单成功',
  welcome: '欢迎再次光临',
  askTable: '桌号是多少',
  askQueue: '取餐号是多少',
  askFee: '茶位费一共多少',
  // delivery (外送)
  address: '收货地址',
  chooseAddress: '选择收货地址',
  arrive: '预计送达',
  minOrder: '起送',
  short: '差',
  promo: '满减',
  cutlery: '餐具数量',
  noCutlery: '无需餐具',
  sets: '份',
  riding: '骑手正在赶来',
  accepted: '商家已接单',
  askArrive: '几点送到',
  cutleryFee: '餐具',
  teaFee: '茶位费',
  mild: '微辣',
  medium: '中辣',
  hot: '特辣',
} as const;

export const KIT_STRINGS: string[] = Object.values(S);

/** Every screen the kit can show; each brand's flow must name them all. */
export const KIT_SCREENS: ScreenId[] = ['chat', 'home', 'menu', 'spec', 'cart', 'checkout', 'pay', 'pickup'];

/** The screens of each way a shop works; each brand's flow must name them all. */
export const SCREENS_OF: Record<'chain' | 'counter' | 'table', ScreenId[]> = {
  chain: KIT_SCREENS,
  counter: KIT_SCREENS,
  table: ['chat', 'landing', 'menu', 'spec', 'cart', 'checkout', 'table', 'bill', 'pay', 'pickup'],
};
